# Generated by Django 4.1.5 on 2023-01-20 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_budget_user_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_expenses',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='total_income',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('FOOD', 'Food'), ('TRANSPORT', 'Transportation'), ('ENTERTAINMENT', 'Entertainment'), ('BILLS', 'Bills'), ('SHOPPING', 'Shopping'), ('HOUSING', 'Housing'), ('MISCELLANEOUS', 'Miscellaneous')], max_length=255),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='base.category'),
        ),
        migrations.AlterField(
            model_name='income',
            name='budget',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income', to='base.budget'),
        ),
    ]
