# Generated by Django 4.1.5 on 2023-01-20 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_report_remaining_balance_report_total_expenses_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavingsGoal',
        ),
    ]
